### ISSUE TITLE
How to run xampp php laravel locally your project without using docker?

### ISSUE THREAD

**Issue by alcatrezA** [krzysztofhewelt/learnin#4]
Your project not run locally xampp using php artisan serve command. Can you please send me proper way to run your project without using docker. Please provide documents for run your project

**Comment by krzysztofhewelt** [comment]
Hello. Apologize for the late reply. I prepared project to run on web server - download v1.0.3. I prepared more detailed installation guide. The easiest way to run this project is described here: https://github.com/krzysztofhewelt/learnin-lms/blob/main/INSTALLATION.md#standard-installation. There is no need to run php artisan serve command on xampp, because it has built-in Apache web server. I suggest run this command only in development mode (default configuration is in .env.dev file, just clone it to .env).
