### ISSUE TITLE
Hosting problem on shared hosting 

### ISSUE THREAD

**Issue by itzharshit** [krzysztofhewelt/learnin#6]
I am having trouble installing it on shared hosting. Can you suggest some steps to host it on shared hosting?

**Comment by krzysztofhewelt** [comment]
What kind of problem is it? I assume that you don't have access to SSH, so you can't install NODE, Composer dependencies and run any command. You must do these steps locally with installed newest version of Node.JS and Composer.

1. Copy ``.env.prod`` file to ``.env``. Configure this configuration file.
* change database credentials - **important**! I would recommend MySQL database.
```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=learnin
DB_USERNAME=root
DB_PASSWORD=superpassword
```
* change URL for app, for example:
```
APP_URL=http://myhosting.com/
```
* **important variables**: app location. I assume you will run app on your main directory on hosting, so you must change these lines to this:
```
BASE_ROOT_DIR=/public
ASSET_URL=/public
BASE_API_URL=/public/api
```

2. Run install.bat (Windows users) or install.sh (Linux users) to install needed dependencies and initialize database.

3. Copy all files to your hosting.

4. If your database is initialized (there are tables in your database) and APP_URL (variable in .env) is configured correctly with your hosting address this app will run and will be on address with /public at the end, ex.: http://myhosting.com/public

I can't add installed dependencies (node_modules and vendor directories) to the repository, because it depends on .env configuration.
If you have any problems, notify me.

**Comment by itzharshit** [comment]
Hello, thank you for your prompt response. I followed all the steps you prescribed, but now I am encountering a different type of error.
Thank you.

`Warning: require(/usr/home/Harshit/domains/course.harshit.wtf/public_html/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /usr/home/Harshit/domains/course.harshit.wtf/public_html/public/index.php on line 34 Warning: require(/usr/home/Harshit/domains/course.harshit.wtf/public_html/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /usr/home/Harshit/domains/course.harshit.wtf/public_html/public/index.php on line 34 Fatal error: Uncaught Error: Failed opening required '/usr/home/Harshit/domains/course.harshit.wtf/public_html/public/../vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/home/Harshit/domains/course.harshit.wtf/public_html/public/index.php:34 Stack trace: #0 {main} thrown in /usr/home/Harshit/domains/course.harshit.wtf/public_html/public/index.php on line 34`

**Comment by krzysztofhewelt** [comment]
That error happens because there are missing Composer dependencies (directory ``vendor`` does not exists). You must install needed dependecies to run app. I assume that you run install.sh/install.bat script and installation did not successful.

[vendor.zip](https://github.com/krzysztofhewelt/learnin-lms/files/13298014/vendor.zip)

I've preapred for you ``vendor`` directory with all needed dependecies. Download it, unpack and copy to app directory (locally, not on hosting - you can't run any commands). I've also preapred .htaccess file, because I see that anyone can access your configuration file ``.env`` (I forgot about that, sorry).

I see, that you did not generate app key and JWT secret. Do also these steps:
1. Go to the project directory and run:
```
php artisan key:generate
php artisan jwt:secret
```
Response should like this:
![1](https://github.com/krzysztofhewelt/learnin-lms/assets/24493324/aa04564e-0c6e-4f56-bd54-16c720006494)


2. Initialize database (create tables in database):
```
php artisan migrate
php artisan db:seed
```

Response should like this:
![2](https://github.com/krzysztofhewelt/learnin-lms/assets/24493324/9924c3b8-275a-4043-b6ca-4ce162a46e56)
![3](https://github.com/krzysztofhewelt/learnin-lms/assets/24493324/1098cf94-ba79-4a03-8727-027fc22a4398)


Now, copy ``vendor`` directory and ``.htaccess`` and ``.env`` files to your hosting.

After this, in your case (you have copied files to your main directory) app should work on address: ``http://course.harshit.wtf/public``. The default administrator credentials is:
login: admin
password: Admin#12345

If you have any problems, notify me.

**Comment by itzharshit** [comment]
I'm sorry to bother you again. Could you please provide me with the `.sql` file so that I can manually upload the tables to the database? It's difficult for me to run the command on my hosting to add the tables cos i am lacking SSH ACCESS.

**Comment by krzysztofhewelt** [comment]
No problem, here is SQL file with database and admin account. 
[database.txt](https://github.com/krzysztofhewelt/learnin-lms/files/13300036/database.txt)

Change extension of file to .sql if needed (i can't upload .sql files here).

**Comment by itzharshit** [comment]
Can you please check it also

SQL Query 

`
create table learnin.courses(    id             bigint unsigned auto_increment        primary key,    name           varchar(60) not null,    description    text        null,    available_from datetime    not null,    available_to   datetime    null)    collate = utf8mb4_unicode_ci;
`

Mysql said
```
#1142 - CREATE command denied to user 'mycamtpc'@'localhost' for table `learnin`.`courses`
```
[sql demo](https://assets.harshit.wtf/dblms.sql.txt)
While uploading tables manually through phpmyadmin i am getting these errors

I guess the sql file you sent have different syntax from other sql files that are used to be uploaded.(i am not sure about it, please check it)
I am attaching a demo sql file for your reference
Thank you so much for your responses.

**Comment by krzysztofhewelt** [comment]
This file should work:
[database.txt](https://github.com/krzysztofhewelt/learnin-lms/files/13300826/database.txt)

I forgot to remove ``learnin.`` that means: create table in ``learnin`` database. I tested in on my local phpmyadmin on MariaDB 10.4.28. It should also work on other MySQL engines.

**Comment by itzharshit** [comment]
![Screenshot_20240214_214615_GitHub.png](https://github.com/krzysztofhewelt/learnin-lms/assets/87630299/c275b2fd-55c3-4c31-807e-f30dd76c9977)


Hello i am just curious to know that how anyone can access .env file because by default the root directory for domain is 
`public` directory. So according to it, anyone can only access the file of public directory not root directory(public_html)

**Comment by krzysztofhewelt** [comment]
In ``.htaccess`` file attached to vendor.zip in first post I wrote one rule that prevents looking in other files and directories except ``public``. Without this (at least I've tested), anyone can look at ``.env`` file and other files/directories.

**Comment by itzharshit** [comment]
> In ``.htaccess`` file attached to vendor.zip in first post I wrote one rule that prevents looking in other files and directories except ``public``. Without this (at least I've tested), anyone can look at ``.env`` file and other files/directories.

i don't want to bother you much but can you please let me know the way to access .env file after deleting `.htaccess` file

**Comment by krzysztofhewelt** [comment]
If you delete .htaccess file in main project directory, there's availability to browse directories in whole project. ``.env`` file is not showed there, but you can access to this file by URL. Try delete this file and access to .env file by URL. Here's what happened after deleting .htacess file in main project directory and trying access to .env file.
![image](https://github.com/krzysztofhewelt/learnin-lms/assets/24493324/6aeaf2a4-0b2e-41f1-8909-9fc8a5b4a35f)
![image](https://github.com/krzysztofhewelt/learnin-lms/assets/24493324/9350629b-0aee-4e45-bffd-15523f5fba5f)

With .htacess rules you can't access this file and other files except ``public`` directory - it will show you 403 Forbidden message. I've already tested in on local XAMPP server. Maybe you've disabled browsing directories globally in main Apache config.
